### ISSUE TITLE
Zope is broken after build with "zope-ecosystem.cfg" (checkout from master)

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#551] opened 2019-04-15 09:35 UTC
```
git clone git@github.com:zopefoundation/Zope.git
bin/pip install -U pip zc.buildout
bin/buildout -c zope-ecosystem.cfg
...
The following part definition lists the versions picked:
[versions]
Products.GenericSetup = 2.0b6
Products.MailHost = 4.5

# Required by:
# Products.CMFCore==2.4.0b8.dev0
Products.StandardCacheManagers = 4.0.2

# Required by:
# Products.TemporaryFolder==5.3.dev0
tempstorage = 4.0.1
...

bin/mkwsgiinstance -d .

bin/runwsgi -v etc/zope.ini 
2019-04-14 23:46:48 INFO [chameleon.config:38][MainThread] directory cache: /home/jugmac00/Projects/Zope/Zope/var/cache.
2019-04-14 23:46:48 ERROR [Products.TemporaryFolder:52][MainThread] Could not initialize a Temporary Folder because a database was not configured to be mounted at the /temp_folder mount point
2019-04-14 23:46:48 INFO [Zope:45][MainThread] Ready to handle requests
Starting server in PID 9297.
Serving on http://localhost:8080
2019-04-14 23:47:08 ERROR [Zope.SiteErrorLog:251][waitress] 1555278428.52544260.46640275815616306 http://localhost:8080/index_html
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 143, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 296, in publish_module
  Module ZPublisher.WSGIPublisher, line 230, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 59, in call_object
  Module Shared.DC.Scripts.Bindings, line 333, in __call__
  Module Shared.DC.Scripts.Bindings, line 370, in _bindAndExec
  Module Products.PageTemplates.ZopePageTemplate, line 274, in _exec
  Module Products.PageTemplates.ZopePageTemplate, line 355, in pt_render
  Module Products.PageTemplates.PageTemplate, line 85, in pt_render
  Module zope.pagetemplate.pagetemplate, line 129, in pt_render
   - Warning: Compilation failed
   - Warning: builtins.AttributeError: module 'importlib' has no attribute 'util'
zope.pagetemplate.pagetemplate.PTRuntimeError: ['Compilation failed', "builtins.AttributeError: module 'importlib' has no attribute 'util'"]
2019-04-14 23:47:08 ERROR [waitress:339][waitress] Exception when serving /
Traceback (most recent call last):
  File "/home/jugmac00/Projects/Zope/Zope/eggs/waitress-1.2.1-py3.6.egg/waitress/channel.py", line 336, in service
    task.service()
  File "/home/jugmac00/Projects/Zope/Zope/eggs/waitress-1.2.1-py3.6.egg/waitress/task.py", line 175, in service
    self.execute()
  File "/home/jugmac00/Projects/Zope/Zope/eggs/waitress-1.2.1-py3.6.egg/waitress/task.py", line 452, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/jugmac00/Projects/Zope/Zope/src/ZPublisher/httpexceptions.py", line 30, in __call__
    return self.application(environ, start_response)
  File "/home/jugmac00/Projects/Zope/Zope/eggs/Paste-3.0.8-py3.6.egg/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/home/jugmac00/Projects/Zope/Zope/src/ZPublisher/WSGIPublisher.py", line 296, in publish_module
    response = _publish(request, new_mod_info)
  File "/home/jugmac00/Projects/Zope/Zope/src/ZPublisher/WSGIPublisher.py", line 230, in publish
    bind=1)
  File "/home/jugmac00/Projects/Zope/Zope/src/ZPublisher/mapply.py", line 85, in mapply
    return debug(object, args, context)
  File "/home/jugmac00/Projects/Zope/Zope/src/ZPublisher/WSGIPublisher.py", line 59, in call_object
    return obj(*args)
  File "/home/jugmac00/Projects/Zope/Zope/src/Shared/DC/Scripts/Bindings.py", line 333, in __call__
    return self._bindAndExec(args, kw, None)
  File "/home/jugmac00/Projects/Zope/Zope/src/Shared/DC/Scripts/Bindings.py", line 370, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/home/jugmac00/Projects/Zope/Zope/src/Products/PageTemplates/ZopePageTemplate.py", line 274, in _exec
    result = self.pt_render(extra_context=bound_names)
  File "/home/jugmac00/Projects/Zope/Zope/src/Products/PageTemplates/ZopePageTemplate.py", line 355, in pt_render
    result = PageTemplate.pt_render(self, source, extra_context)
  File "/home/jugmac00/Projects/Zope/Zope/src/Products/PageTemplates/PageTemplate.py", line 85, in pt_render
    showtal=showtal)
  File "/home/jugmac00/Projects/Zope/Zope/eggs/zope.pagetemplate-4.4.1-py3.6.egg/zope/pagetemplate/pagetemplate.py", line 129, in pt_render
    raise PTRuntimeError(str(self._v_errors))
zope.pagetemplate.pagetemplate.PTRuntimeError: ['Compilation failed', "builtins.AttributeError: module 'importlib' has no attribute 'util'"]
```

**Comment by dataflake** [comment] 2019-04-15 12:23
I'll take a look later. Was that a fresh/empty ZODB or did it have content already?

**Comment by jugmac00** [comment] 2019-04-15 12:41
This was a complete fresh installation + empty ZODB.

P.S.: I tried the "ecosystem" setup, as in a plain Zope setup I could not validate the behaviour of
https://zope.readthedocs.io/en/latest/zdgbook/ObjectPublishing.html#calling-the-published-object
as in the plain Zope setup I seemingly cannot create a Python script in the db (4.0b1 dropped PythonScripts).

I am not 100% sure whether it is a good idea to be able to create page templates, dtml methods/documents, but no Python script in a vanilla Zope setup. But that's another topic.

**Comment by dataflake** [comment] 2019-04-15 13:22
This is a really odd one. First of all, it only happened on first access. I stopped the Zope instance to put in some debugging code in zope.pagetemplate, but when I restarted the issue did not appear. I could only reproduce it after deleting the ZODB so a new one gets created.

The traceback I got after removing the masking the page template code does actually points to an error inside Python 3.6 itself, see below.

I'll try upgrading my installation to 3.6.8 now and see if that solves the issue.

```
Traceback (most recent call last):
  File "bin/runwsgi", line 102, in <module>
    sys.exit(Zope2.Startup.serve.main())
  File "/Users/jens/Desktop/Zope/src/Zope2/Startup/serve.py", line 217, in main
    return command.run()
  File "/Users/jens/Desktop/Zope/src/Zope2/Startup/serve.py", line 184, in run
    global_conf=vars)
  File "/Users/jens/Desktop/Zope/src/Zope2/Startup/serve.py", line 208, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/Users/jens/src/.eggs/PasteDeploy-2.0.1-py3.6.egg/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/Users/jens/src/.eggs/PasteDeploy-2.0.1-py3.6.egg/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "/Users/jens/src/.eggs/PasteDeploy-2.0.1-py3.6.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/Users/jens/src/.eggs/PasteDeploy-2.0.1-py3.6.egg/paste/deploy/loadwsgi.py", line 209, in invoke
    app = context.app_context.create()
  File "/Users/jens/src/.eggs/PasteDeploy-2.0.1-py3.6.egg/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/Users/jens/src/.eggs/PasteDeploy-2.0.1-py3.6.egg/paste/deploy/loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/Users/jens/src/.eggs/PasteDeploy-2.0.1-py3.6.egg/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/Users/jens/Desktop/Zope/src/Zope2/Startup/run.py", line 68, in make_wsgi_app
    starter.prepare()
  File "/Users/jens/Desktop/Zope/src/Zope2/Startup/starter.py", line 41, in prepare
    self.startZope()
  File "/Users/jens/Desktop/Zope/src/Zope2/Startup/starter.py", line 97, in startZope
    Zope2.startup_wsgi()
  File "/Users/jens/Desktop/Zope/src/Zope2/__init__.py", line 50, in startup_wsgi
    _startup()
  File "/Users/jens/Desktop/Zope/src/Zope2/App/startup.py", line 153, in startup
    OFS.Application.initialize(application)
  File "/Users/jens/Desktop/Zope/src/OFS/Application.py", line 199, in initialize
    initializer.initialize()
  File "/Users/jens/Desktop/Zope/src/OFS/Application.py", line 224, in initialize
    self.install_root_view()
  File "/Users/jens/Desktop/Zope/src/OFS/Application.py", line 296, in install_root_view
    root_pt = ZopePageTemplate('index_html')
  File "/Users/jens/Desktop/Zope/src/Products/PageTemplates/ZopePageTemplate.py", line 120, in __init__
    self.pt_edit(text, content_type)
  File "/Users/jens/Desktop/Zope/src/Products/PageTemplates/ZopePageTemplate.py", line 141, in pt_edit
    super(ZopePageTemplate, self).pt_edit(text_decoded, content_type)
  File "/Users/jens/src/.eggs/zope.pagetemplate-4.4.1-py3.6.egg/zope/pagetemplate/pagetemplate.py", line 99, in pt_edit
    self.write(text)
  File "/Users/jens/Desktop/Zope/src/Products/PageTemplates/ZopePageTemplate.py", line 242, in write
    ZopePageTemplate.inheritedAttribute('write')(self, text)
  File "/Users/jens/src/.eggs/zope.pagetemplate-4.4.1-py3.6.egg/zope/pagetemplate/pagetemplate.py", line 180, in write
    self._cook()
  File "/Users/jens/src/.eggs/zope.pagetemplate-4.4.1-py3.6.egg/zope/pagetemplate/pagetemplate.py", line 230, in _cook
    source_file, self._text, pt_engine, self.content_type)
  File "/Users/jens/Desktop/Zope/src/Products/PageTemplates/engine.py", line 126, in cook
    encoding='utf-8', extra_builtins=cls.extra_builtins,
  File "/Users/jens/src/.eggs/Chameleon-3.6-py3.6.egg/chameleon/zpt/template.py", line 200, in __init__
    super(PageTemplate, self).__init__(body, **config)
  File "/Users/jens/src/.eggs/Chameleon-3.6-py3.6.egg/chameleon/template.py", line 132, in __init__
    self.write(body)
  File "/Users/jens/src/.eggs/Chameleon-3.6-py3.6.egg/chameleon/template.py", line 227, in write
    self.cook(body)
  File "/Users/jens/src/.eggs/Chameleon-3.6-py3.6.egg/chameleon/template.py", line 162, in cook
    program = self._cook(body, digest, names)
  File "/Users/jens/src/.eggs/Chameleon-3.6-py3.6.egg/chameleon/template.py", line 243, in _cook
    cooked = self.loader.build(source, filename)
  File "/Users/jens/src/.eggs/Chameleon-3.6-py3.6.egg/chameleon/loader.py", line 177, in build
    py_compile.compile(name)
  File "/Users/jens/src/Python-3.6.6/lib/python3.6/py_compile.py", line 112, in compile
    cfile = importlib.util.cache_from_source(file)
AttributeError: module 'importlib' has no attribute 'util'
```

**Comment by dataflake** [comment] 2019-04-15 13:42
I wasn't able to build 3.6.8 (for some reason `configure` complains that the C compiler doesn't work right) but I have also tests this on 3.7.3 and the same error happens.

The issue happens whenever a template is getting compiled. It goes away after a Zope restart and reappears as soon as the template is changed or you create a new one.

I'll look into filing an issue on the Python issue tracker.

**Comment by dataflake** [comment] 2019-04-15 13:52
Here's the Python bug tracker issue: https://bugs.python.org/issue36633

**Comment by dataflake** [comment] 2019-04-15 14:31
Turns out this is not a bug in Python. It's something I introduced myself in https://github.com/zopefoundation/Products.PythonScripts/commit/407a550cf59b2c983300a4a3055b457bfbfdba41 when I just copied the previous behavior (import the module, run a quick check, delete it). Removing the deletion fixes the error.

I'll close this issue and track the actual fix at https://github.com/zopefoundation/Products.PythonScripts/issues/27

**Closed by dataflake** 2019-04-15 14:31 UTC
Labels: bug

**Comment by dataflake** [comment] 2019-04-15 14:41
If you go into your checkout's `develop/Products.PythonScripts` folder and do a `git pull` you'll get the fix. Restart the Zope instance after that and you can continue working.

**Comment by dataflake** [comment] 2019-04-15 14:47
Release 4.6 now at at https://pypi.org/project/Products.PythonScripts/

**Comment by jugmac00** [comment] 2019-04-15 20:18
Thanks a ton! Now, I am able to access Zope via my browser.
