### ISSUE TITLE
Zope's project description on pypi does not get rendered properly

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#517] opened 2019-02-20 08:18 UTC
https://pypi.org/project/Zope/

also see attached screenshot

![screenshot from 2019-02-20 09-17-35](https://user-images.githubusercontent.com/9895620/53076665-80403e00-34f0-11e9-84a3-07cf8c9e5231.png)

**Comment by dataflake** [comment] 2019-02-20 12:53
@icemac Could it be this wasn't caught by running `bin/longtest` before the release? Running it on current `master` renders fine.

**Comment by dataflake** [comment] 2019-02-23 17:47
I just checked out the tag `4.0b9` and there is a problem:

```
$ bin/longtest
ERROR: Error generating html. Invalid ReST.
/var/folders/jq/51f_s8vs5wz2hjlvrx0b9qhh0000gn/T/tmptwbf61l5.rst:79: (WARNING/2) Bullet list ends without a blank line; unexpected unindent.
```

I don't see a way to change the log description on PyPI before the next release, we'll just have to live with it. The issue is solved on `master`, so I am closing this task as resolved.

**Closed by dataflake** 2019-02-23 17:47 UTC

**Comment by jugmac00** [comment] 2019-02-23 20:01
Thanks - just saw bin/longtest is already documented as a mandatory step for a new release @ maintenance.rst. So there is nothing to do for now. Following many manual steps always means there is a risk to forget one.

Thanks for explaining how you tracked down the problem.

**Comment by icemac** [comment] 2019-02-26 07:26
Sorry, I must have left out the step to check the long description. And yes, we cannot do anything right now. The next release should fix it.
