### ISSUE TITLE
create another exact copy of a zope instance

### ISSUE THREAD

**Issue by naveenkrify** [zopefoundation/Zope#793] opened 2020-02-28 04:35 UTC
How to create another exact copy of a zope instance running along with data. I have already tried copying old Data.fs to a new zope instance but it didn't work.

**Comment by viktordick** [comment] 2020-02-28 05:25
What exactly are you trying to accomplish? A fork of the `Data.fs`, so both use the same data as a starting point and can diverge afterwards? Or should they use the same data and simply serve on different ports, for load balancing or similar?

In the first case, copying the `Data.fs` usually works. In the second, you need to setup a `ZEO` server that handles the `Data.fs`, with `Zope` instances connecting to it.

**Comment by naveenkrify** [comment] 2020-02-28 06:43
Hi viktordick thanks for the quick reply
I'm trying to move the zope Instance to another server. Could you please give me a more detail explanation of moving zope instance to another server. I'm quite new to zope

**Comment by d-maurer** [comment] 2020-02-28 08:00
naveenkrify wrote at 2020-2-27 22:43 -0800:
>Hi viktordick thanks for the quick reply
>I'm trying to move the zope Instance to another server. Could you please give me a more detail explanation of moving zope instance to another server. I'm quite new to zope

A Zope instance consists of code and data.

The data is usually stored in "Data.fs"; but your application
(on top of Zope) may store its data at a different place or
at additional places (e.g. a relational database).

The code consists of the Zope code proper and potentially
extensions, either general extensions or extensions specific for
your application. There are different ways, how you install
the Zope code, most prominent via `buildout` or `virtualenv + pip`.
Typically this also affects how extensions are installed.
And how you transfer the code base also depends on the installation
method.

In general: to move a Zope instance, install Zope and all relevant
extensions in the new place - taking care to ensure that the same
versions are used. This is quite easy when you use `buildout` and
so called "version pins" for all extensions.
Then copy over the data.

**Comment by naveenkrify** [comment] 2020-02-28 10:19
Thank you  d-maurer for the clarification 

Could you please share the link of the in-detail tutorial. I'm using a quite old zope and python(Zope - 2.10.6, Python - 2.4)

**Comment by d-maurer** [comment] 2020-02-28 10:35
naveenkrify wrote at 2020-2-28 02:19 -0800:
>Could you please share the link of the in-detail tutorial. I'm using a quite old zope and python(Zope - 2.10.6, Python - 2.4)

I fear I cannot. If you are lucky, then your current Zope installation
contains a "doc" folder with installation instructions. Follow them.
If not, you must try to find a source distribution for your historical
Zope and look there for the installation instructions.

But, really, you should consider to modernize your installation --
at least to Python 2.7.x, Zope 2.13.x. Note that Python 2 support has
already terminated and you may even consider to switch to Zope 4.x
(first with Python 2.7 and in a second step with Python 3.6+).

**Comment by naveenkrify** [comment] 2020-02-28 11:01
I already have the source distribution and I installed and made a sample instance but I'm stuck at moving the code and data. Thanks again

**Comment by d-maurer** [comment] 2020-02-28 11:11
naveenkrify wrote at 2020-2-28 03:01 -0800:
>I already have the source distribution and I installed and made a sample instance but I'm stuck at moving the code and data. Thanks again

What went wrong after you have copied the "Data.fs"?

That you have installed "a sample instance" means that you
have the Zope code proper. Your application (on to of Zope)
may use extensions (also called "Products"). If the new instance
lacks those extensions, then your application may not work.

In historical Zope versions (such as yours), extensions were
typically located in a folder called "Products". Copy its content over
as well. Zope applications may also make use of so called
"ExternalMethod"s; their code can be either located inside a "Product"
(then you have copied it in the previous step) or in a folder
likely called "Extensions". If it should not be empty, copy its content
over to the new instance.

**Comment by naveenkrify** [comment] 2020-02-29 14:03
Hi, @d-maurer  I have transferred Data.fs, Extensions, and Products. I have tried to run it and running without any issues but how do I transfer code? 
Many Thanks in advance.

**Comment by d-maurer** [comment] 2020-02-29 15:57
naveenkrify wrote at 2020-2-29 06:03 -0800:
>Hi, @d-maurer  I have transferred Data.fs, Extensions, and Products. I have tried to run it and running without any issues but how do I transfer code?

Likely, you have (already) transfered the code.

As I have explained earlier (reread, if necessary), the code
of a Zope application consists of the Zope code proper
(transfered by installing Zope) and extensions  - in historical
Zope installations the extensions are typically stored in `Products` and
(potentially) `Extensions` (transfered explicitly).

If your Zope (and your application on top) "runs without issues",
everything worked perfect. If not, come back
(but this place is more a bug tracker, not a place to get general
help; use the "Zope" topic on "https://community.plone.org" for help).

**Comment by icemac** [comment] 2020-03-02 09:59
BTW the latest releases of old Zope versions are on https://zopefoundation.github.io/Zope/ (scroll down to the bottom to see them.)

**Comment by icemac** [comment] 2020-03-02 10:00
Closing the issue as it is not a bug/feature/etc. and @d-maurer already pointed to the forum.

**Closed by icemac** 2020-03-02 10:00 UTC
Labels: question
