### ISSUE TITLE
zope.org down

### ISSUE THREAD

**Issue by taenzerme** [zopefoundation/Zope#162] opened 2017-09-05 12:37 UTC
Hey all,

as it seems zope.org is down for some time now. 

I don't know who's taking care of this but it would be great to get it back online :-)

Thanks!

Best
Sebastian

**Comment by hannosch** [comment] 2017-09-05 12:47
Well, nobody is taking care of it really. That's why the few of us still around have been trying to move everything away from the server and onto services likes readthedocs or github.io pages.

@jimfulton might be our best bet on, who might be able to get the box up again. It seems it's down hard and not responding to a ping. I'd have ssh access into the box if it was up.

@taenzerme is there something specific you were looking for on the box? For example version files should be available either directly from Github tags or via https://dist.plone.org/versions/

**Comment by jimfulton** [comment] 2017-09-05 12:54
Technically, zope.org is up. :)  The machine with various services on it.
most notably mail.zope.org and doc.zope.org is down.

On Tue, Sep 5, 2017 at 8:47 AM, Hanno Schlichting <notifications@github.com>
wrote:

> Well, nobody is taking care of it really. That's why the few of us still
> around have been trying to move everything away from the server and onto
> services likes readthedocs or github.io pages.
>
We need to try harder. :)

> @jimfulton <https://github.com/jimfulton> might be our best bet on, who
> might be able to get the box up again. It seems it's down hard and not
> responding to a ping. I'd have ssh access into the box if it was up.
>
There's nothing I can do atm.  I'm somewhat hopeful that it will come back
due to other folks' efforts.

**Comment by taenzerme** [comment] 2017-09-05 13:12
Hey, thanks for the quick response. One of my coworkers is looking into Zope and ZMS3 (CMS based on Zope2) and was looking for the documentation aka "The Zope Book" (which, btw, still sits on my shelf as printed first edition).  

If it helps in any way: My company is running a big Proxmox cluster here in Bonn, Germany, and we could provide a server for free if needed. But from what I understand readthedocs would be the better solution IMHO.

Thanks for your efforts! If anyone of you has a copy of https://docs.zope.org/zope2 somewhere I'd be really happy :-)

**Comment by taenzerme** [comment] 2017-09-06 10:41
Sorry for "bumping" this again, but if anyone of you does have a static (as in "offline") copy of the docs it would be great to share these as a download here or somewhere else online. The wayback archives actually do not help, too, as all links do go to the original domain.

**Comment by jimfulton** [comment] 2017-09-06 13:17
The sites are back up.

**Comment by taenzerme** [comment] 2017-09-06 13:17
Perfect, thanks for your help.

**Comment by Julian** [comment] 2017-12-06 18:10
Seems like it's down again.

**Comment by taenzerme** [comment] 2017-12-13 21:06
Yup, down again. Not really sure why. @jimfulton Any chance to put the docs source to github, too?

**Comment by hannosch** [comment] 2017-12-13 22:22
The zope book is available at http://zope.readthedocs.io/en/latest/zope2book/index.html for a while now

**Comment by jimfulton** [comment] 2017-12-13 22:53
And www.zope.org: http://wwwzopeorg.readthedocs.io/en/latest/ :-)

We don't control the domain registration for hysterical reasons.

I'm hopeful that will be resolved soon.

**Comment by Julian** [comment] 2017-12-13 23:00
The problem is just that those don't show up high in Google results :/...

**Comment by mck9** [comment] 2017-12-18 20:35
download.zope.org is also gone. Plone depends on it. Any way to resolve it? Is there an alternative hostname available?

**Comment by jimfulton** [comment] 2017-12-18 20:54
Well, the IP is 46.4.103.110.  If someone want to set up a domain (perhaps a plone.org subdomain) that points to that, I'll set up a virtual host for it on that machine. (The machine is fine, it's the zope.org registration that's the problem.)

I'm hopeful that the zope.org registration mess will get resolved in a week or 2, but who knows.

**Comment by icemac** [comment] 2018-01-17 09:17
Both zope.org and download.zope.org are back online. Thank you to everyone who made it possible.

**Closed by icemac** 2018-01-17 09:17 UTC
