### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'instance home' zope2

### ISSUE THREAD

**Issue by naveenkrify** [zopefoundation/Zope#685] opened 2019-08-14 04:47 UTC
While I was starting the zope I faced the following error message
AttributeError: 'NoneType' object has no attribute 'instance home' zope2

**Comment by icemac** [comment] 2019-08-14 06:28
Thank you for reporting this issue.
To reproduce it we need more details about your installation and the issue:
* Which version of Zope did you use?
* How did you install it?
* Did you use any add-ons, Products, additional Python packages?
* How does your zope.conf file look like?

**Comment by dataflake** [comment] 2019-09-02 17:01
Since this is completely unsubstantiated and there was no reaction at all to further questions I am going to close this.

**Closed by dataflake** 2019-09-02 17:01 UTC
Labels: feedback required

**Comment by naveenkrify** [comment] 2020-11-20 07:55
Hello Guys, 

Sorry for the very late reaction. I'm still facing the same issue.

Zope version 2.10.9

Python version 2.4

Actually This zope was installed using python2.4 . But when I'm running zopectl it was using python2.7


Traceback (most recent call last):
  File "/usr/local/bin/zopectl", line 9, in <module>
    load_entry_point('Zope2==2.13.22', 'console_scripts', 'zopectl')()
  File "/usr/local/lib/python2.7/dist-packages/Zope2/Startup/zopectl.py", line 484, in run
    exitstatus = main()
  File "/usr/local/lib/python2.7/dist-packages/Zope2/Startup/zopectl.py", line 440, in main
    options.realize(args)
  File "/usr/local/lib/python2.7/dist-packages/Zope2/Startup/zopectl.py", line 180, in realize
    self.directory = config.instancehome
AttributeError: 'NoneType' object has no attribute 'instancehome'

**Comment by d-maurer** [comment] 2020-11-20 09:02
naveenkrify wrote at 2020-11-19 23:55 -0800:
> ...
>Actually This zope was installed using python2.4 . But when I'm running zopectl it was using python2.7
>Traceback (most recent call last):
> ...
>  File "/usr/local/lib/python2.7/dist-packages/Zope2/Startup/zopectl.py", line 180, in realize
>    self.directory = config.instancehome
>AttributeError: 'NoneType' object has no attribute 'instancehome'

Apparently, `config` is `None`.
Look at the code to determine where `config` comes from and
why it may be `None` unexpectedly. I would use the Python debugger
if necessary to determine the problem cause.

**Comment by naveenkrify** [comment] 2020-11-20 10:19
@d-maurer thanks for the idea. 

 The problem was solved. The issue is two zope versions installed in that server. 

when I'm using zopectl command it was actually another zope version. So I removed the other and it was worked perfectly
