### ISSUE TITLE
Plone 5.2 rc3 / Zope 4.0b10 on Python 3.6.x: DateTime Error in portal_catalog

### ISSUE THREAD

**Issue by andreasma** [zopefoundation/Zope#645] opened 2019-05-31 10:41 UTC
I created a new Plone instance from Plone 5.2 rc3 and took a look into the indexes of the portal_catalog. If I try to browse in the indexes for 'created', 'effective', 'modified' and 'expired' I get only error messages with tracebacks similar to the following:

2019-05-31 11:03:38,299 ERROR [Zope.SiteErrorLog:251][waitress] 1559293418.29886650.8541733846348719 http://localhost:58585/[plone-site-name]/portal_catalog/Indexes/created/manage_browse
Traceback (innermost last):
Module ZPublisher.WSGIPublisher, line 142, in transaction_pubevents
Module ZPublisher.WSGIPublisher, line 295, in publish_module
Module ZPublisher.WSGIPublisher, line 229, in publish
Module ZPublisher.mapply, line 85, in mapply
Module ZPublisher.WSGIPublisher, line 57, in call_object
Module Shared.DC.Scripts.Bindings, line 330, in call
Module Shared.DC.Scripts.Bindings, line 367, in _bindAndExec
Module App.special_dtml, line 203, in _exec
Module DocumentTemplate._DocumentTemplate, line 147, in render_blocks
Module DocumentTemplate.DocumentTemplate, line 248, in render_blocks
Module DocumentTemplate.DT_Let, line 84, in render
Module DocumentTemplate._DocumentTemplate, line 147, in render_blocks
Module DocumentTemplate.DocumentTemplate, line 248, in render_blocks
Module DocumentTemplate.DT_In, line 642, in renderwb
Module DocumentTemplate._DocumentTemplate, line 147, in render_blocks
Module DocumentTemplate.DocumentTemplate, line 230, in render_blocks
Module DocumentTemplate.DocumentTemplate, line 171, in render_blocks
Module DocumentTemplate.DT_Util, line 228, in eval

    traceback_info: _
    Module , line 1, in
    Module DateTime.DateTime, line 447, in init
    File "", line None

SyntaxError: Unable to parse (2019.3515568996415, 5.186424731182342, 6.779166666674428, 18.699999999254942, 42, 0, 'UTC'), {}

**Comment by zopyx** [comment] 2019-05-31 11:20
Confirmed

**Comment by dataflake** [comment] 2019-09-02 18:35
The issue is invalid values stored in the indices. Here's what it should look like from a Python 2 sandbox:

`(2019, 9, 2, 18, 16, 0, 'UTC')`

Notice how the year, month, day and hour values in the traceback are floats? That feels like those methods (Date, created, etc) return wrong data.

I don't see how this is a Zope issue.

**Comment by dataflake** [comment] 2019-10-13 16:30
Closing as invalid. The issue appears because invalid values got stored in those indices. This is not a Zope issue.

**Closed by dataflake** 2019-10-13 16:30 UTC
Labels: feedback required, invalid
