### ISSUE TITLE
Zope5.0: WARNING: The wheel package is not available

### ISSUE THREAD

**Issue by gpzope** [zopefoundation/Zope#920] opened 2020-10-14 07:11 UTC
### What I did:
When I tried to install Zope-5.0 following the direction here: https://zope.readthedocs.io/en/latest/INSTALL.html
with Built-in standard buildout configuration I got: WARNING: The wheel package is not available

So, what I did was:

```
wget https://pypi.org/packages/source/Z/Zope/Zope-5.0.tar.gz
tar xfvz Zope-5.0.tar.gz
cd Zope-5.0
python3.9 -m venv .
bin/pip install wheel
bin/pip install -U pip zc.buildout
bin/buildout
```
And it worked just fine!

**Edit by jugmac00**
- fixed formatting
- note: the difference between the working and not working approach is installing `wheel` manually

**Comment by jugmac00** [comment] 2020-10-14 08:38
While at first sight, this seems not to be a Zope problem, as we have no influence on how your venv is setup.

When googling for this very error message, I found the following entry by @pganssle ( https://github.com/pypa/setuptools/issues/1934#issuecomment-561938312 ) which suggest, this could be fixed on our side by shipping a pyproject.toml. Buut.. this should not be necessary as we do ship wheels - see here https://pypi.org/project/Zope/#files

That said, I tried to reproduce the problem both with `virtualenv` and `venv` and I cannot reproduce any problem.

P.S.: @gpzope please provide the complete traceback

**Closed** 2020-10-14 10:43 UTC

**Comment by dataflake** [comment] 2020-10-14 10:46
There's no actual problem here. If the virtual environment does not have access to `wheel` you will see a warning because some packages are installed from tarball eggs instead of wheels. The buildout will always succeed.

This is essentially a documentation issue. I have updated the install documentation to install `wheel` alongside `zc.buildout` after initializing the virtual environment and before running the buildout.
