### ISSUE TITLE
Unmet dependency on Paste

### ISSUE THREAD

**Issue by dwt** [zopefoundation/Zope#452] opened 2019-01-09 10:20 UTC
When installing the current master from source (via https://github.com/zopefoundation/Zope/blob/master/requirements-full.txt) , it doesn't come up, as it requires Paste to be installed - which isn't.

Stacktrace looks like this:
```
(venv:zope-zms-py3) dwt@nathan ~/Code/Projekte/zope4 % bin/local_run_zope.sh 
Traceback (most recent call last):
  File "/Users/dwt/.virtualenvs/zope-zms-py3/bin/runwsgi", line 11, in <module>
    load_entry_point('Zope', 'console_scripts', 'runwsgi')()
  File "/Users/dwt/.virtualenvs/zope-zms-py3/src/zope/src/Zope2/Startup/serve.py", line 216, in main
    return command.run()
  File "/Users/dwt/.virtualenvs/zope-zms-py3/src/zope/src/Zope2/Startup/serve.py", line 183, in run
    global_conf=vars)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/src/zope/src/Zope2/Startup/serve.py", line 207, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 277, in loadobj
    global_conf=global_conf)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 302, in loadcontext
    global_conf=global_conf)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 326, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 455, in get_context
    global_additions=global_additions)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 567, in _pipeline_app_context
    for name in pipeline[:-1]]
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 567, in <listcomp>
    for name in pipeline[:-1]]
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 459, in get_context
    section)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 481, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 412, in get_context
    global_conf=global_conf)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 302, in loadcontext
    global_conf=global_conf)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 334, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 625, in get_context
    object_type, name=name)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 645, in find_egg_entry_point
    pkg_resources.require(self.spec)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Paste' distribution was not found and is required by the application
```

It looks a bit like PasteDeploy might be the culprit here that is missing a dependency, but since their tests are all green and an overview inspection of their repo doesn't seem to suggest that they removed a dependency (I may be wrong on this though) made me report the bug first here.

Just running `pip install paste` seems to work around this.

**Comment by icemac** [comment] 2019-01-11 07:11
@dwt Thank you for your report.

Can you paste the steps to create a Zope instance where the exception happens?
What are the contents of your `bin/local_run_zope.sh` script?

I did the following and was not able to reproduce the exception:

```
$ pyvenv-3.7 z4
WARNING: the pyenv script is deprecated in favour of `python3.7 -m venv`
$ cd z4
$ bin/pip install -r https://raw.githubusercontent.com/zopefoundation/Zope/master/requirements-full.txt
...
$  bin/mkwsgiinstance -d .
...
$ bin/runwsgi etc/zope.ini
Starting server in PID 56474.
Serving on http://localhost:8080
```

Using the shown URL in a browser works, too.

**Comment by dataflake** [comment] 2019-02-09 02:21
@icemac I recommend closing this as invalid. No one else has seen this issue and @dwt is not providing any more information.

**Comment by icemac** [comment] 2019-02-09 09:02
Closing as invalid as @dataflake suggested: It cannot be reproduced and there was no feedback from @dwt. Please reopen if the issue still persists and you have new details about it.

**Comment by icemac** [comment] 2019-06-17 06:17
This is reproducible now:

```bash
python3.6 -m venv zope4.0
cd zope4.0
bin/pip install -r https://zopefoundation.github.io/Zope/releases/4.0/requirements-full.txt
bin/mkwsgiinstance -d .
bin/runwsgi -v etc/zope.ini
```

leads to `pkg_resources.DistributionNotFound: The 'Paste' distribution was not found and is required by the application`.

Paste is needed because we use `egg:Paste#translogger` in `etc/zope.ini`. So I'd suggest to add `Paste` to `versions-prod.cfg` so it will appear in `requirements-full.txt` after running buildout.

**Closed** 2019-06-18 06:20 UTC
Labels: RELEASE BLOCK, bug

**Comment by ghiodor** [comment] 2019-06-25 20:21
This is still present in 4.1

**Comment by icemac** [comment] 2019-06-26 05:46
@ghiodor It should be fixed in 4.1 as the `requirements-full.txt` of 4.1 contains `Paste`, see https://zopefoundation.github.io/Zope/releases/4.1/requirements-full.txt

If it does not work for you please show the steps to reproduce the issue.

**Comment by ghiodor** [comment] 2019-06-27 07:22
history:
```
 2161  python3.8 -m venv zope
 2162  cd zope 
 2163  cp ../buildout.cfg 
 2164  cp ../buildout.cfg .
 2165  bin/pip install -U pip zc.buildout
 2166  bin/buildout
 2167  bin/mkwsgiinstance 
 2168  vim etc/zope.ini
 2169  bin/runwsgi -v etc/zope.ini

```
and buildout.cfg:

```
[buildout]
extends = https://zopefoundation.github.io/Zope/releases/4.1/versions-prod.cfg
parts = zopescripts

[zopescripts]
recipe = zc.recipe.egg
interpreter = zopepy
eggs =
  Zope
#  Paste
  Products.TemporaryFolder
  Products.ExternalMethod
  Products.PythonScripts
  Products.Sessions
  Products.SiteErrorLog
  Products.MailHost
  Products.ZSQLMethods
  Products.ZMySQLDA

```

**Comment by ghiodor** [comment] 2019-06-27 07:23
Listing Paste (currently commented out) in the eggs, works.

**Comment by icemac** [comment] 2019-06-28 05:38
@ghiodor I was able to reproduce the problem and created a new ticket for this issue: #664
