### ISSUE TITLE
error_log in Zope4: list of "ignored exceptions" converted to bytes-per-line

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Zope#453] opened 2019-01-09 15:04 UTC
If you update the list of ignored exceptions in Zope 4 then they will show up after saving as bytes-per-line.

![screenshot-dev zopyx de 20080-2019-01-09-16-03-57](https://user-images.githubusercontent.com/594239/50907660-357ad300-1428-11e9-9c8c-9da904cd3425.png)

**Comment by icemac** [comment] 2019-01-11 07:13
This should have been fixed in zopefoundation/Products.SiteErrorLog#14.
What version of Products.SiteErrorLog are you using?

**Comment by dataflake** [comment] 2019-02-09 02:19
I'm going to close this as Invalid because

- the issue does not belong here, it belongs into `Products.SiteErrorLog`
- it has already been fixed there as @icemac said, which I just confirmed myself in a Zope 4 buildout under both Python 2 and Python 3

If Plone does still pin to a version <5.1 please take it up with them.

**Closed by dataflake** 2019-02-09 02:19 UTC
Labels: invalid
